##############################################################################
# Role: yum_install - START
##############################################################################

# Repositories to add using yum-config-manager
#
repos_to_add:
  - https://download.docker.com/linux/centos/docker-ce.repo

# Every package is defined with its name and state - so we
# can have possibility to remove or update package if needed.
#
# Also packages can have svc dict assigned with them, if
# we need to enable and start service after package installation.
#
yum_packages_to_install:
  - name: epel-release
    state: present
  - name: yum-utils
    state: present
  - name: device-mapper-persistent-data
    state: present
  - name: lvm2
    state: present
  - name: containerd.io
    state: present
  - name: docker-ce-3:18.09.1-3.el7
    state: present
    svc:
      name: docker
      enabled: yes
      svc_state: started
  - name: docker-ce-cli
    state: present
  - name: python3
    state: present
  - name: net-tools
    state: present
  - name: wget
    state: present
  - name: unzip
    state: present
  - name: bind
    state: present
  - name: bind-utils
    state: present

##############################################################################
# Role: yum_install - END
##############################################################################



##############################################################################
# Role: setup_docker - START
##############################################################################

# Docker services to run with docker compose
#
docker_svcs:
  - name: prometheus
    image: prom/prometheus
    container_name: prometheus
    ports: 
      - "9090:9090/tcp"
    volumes: 
      - "/tmp/prometheus.yml:/etc/prometheus/prometheus.yml"
  - name: alertmanager
    image: prom/alertmanager
    container_name: alertmanager
    ports:
      - "9093:9093/tcp"
  - name: grafana
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000/tcp"
    volumes:
      - "/tmp/grafana.ini:/etc/grafana/grafana.ini"
      - "/tmp/prometheus_datasource.yml:/etc/grafana/provisioning/datasources/prometheus_datasource.yml"
      - "/tmp/dashboards_provisioning.yml:/etc/grafana/provisioning/dashboards/dashboards_provisioning.yml"
      - "/tmp/node_exporter_dashboard.json:/var/lib/grafana/dashboards/node_exporter_dashboard.json"
      - "/tmp/process_exporter_dashboard.json:/var/lib/grafana/dashboards/process_exporter_dashboard.json"
  - name: nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - "/tmp/nginx.conf:/etc/nginx/conf.d/default.conf"
  - name: cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

##############################################################################
# Role: setup_docker - END
##############################################################################