##############################################################################
# Role: yum_install - START
##############################################################################

# Repositories to add using yum-config-manager
#
repos_to_add:
  - https://download.docker.com/linux/centos/docker-ce.repo

# Every package is defined with its name and state - so we
# can have possibility to remove or update package if needed.
#
# Also packages can have svc dict assigned with them, if
# we need to enable and start service after package installation.
#
yum_packages_to_install:
  - name: epel-release
    state: present
  - name: yum-utils
    state: present
  - name: device-mapper-persistent-data
    state: present
  - name: lvm2
    state: present
  - name: containerd.io
    state: present
  - name: docker-ce-3:18.09.1-3.el7
    state: present
    svc:
      name: docker
      enabled: yes
      svc_state: started
  - name: docker-ce-cli
    state: present
  - name: python3
    state: present
  - name: net-tools
    state: present
  - name: wget
    state: present
  - name: unzip
    state: present
  - name: postfix
    state: present
    svc:
      name: postfix
      enabled: yes
      svc_state: started
  - name: dovecot
    state: present
    svc:
      name: dovecot
      enabled: yes
      svc_state: started

##############################################################################
# Role: yum_install - END
##############################################################################



##############################################################################
# Role: setup_docker - START
##############################################################################

# Docker services to run with docker compose
#
docker_svcs:
  - name: nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - "/tmp/nginx.conf:/etc/nginx/conf.d/default.conf"
  - name: cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

##############################################################################
# Role: setup_docker - END
##############################################################################



##############################################################################
# Role: setup_email_server - START
##############################################################################

# Lines to be entered with lineinfile module
#
lines_in_file:
  - file: /etc/postfix/main.cf
    lines:
      - inet_interfaces = all
      - myhostname = mail.{{ zone_name }}
      - mydomain = {{ zone_name }}
      - myorigin = {{ zone_name }}
      - mydestination = {{ zone_name }}, \$myhostname, localhost.\$mydomain, localhost
      - smtpd_tls_cert_file = /vagrant/ssh/MyCertificate.crt
      - smtpd_tls_key_file = /vagrant/ssh/MyKey.key
      - smtpd_tls_loglevel = 1
      - smtp_tls_loglevel = 1
      - smtpd_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
      - smtpd_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
      - smtp_tls_mandatory_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
      - smtp_tls_protocols = !SSLv2, !SSLv3, !TLSv1, !TLSv1.1
      - mailbox_transport = lmtp:unix:private/dovecot-lmtp
      - smtputf8_enable = no
  - file: /etc/dovecot/dovecot.conf
    lines:
      - protocols = imap lmtp
  - file: /etc/dovecot/conf.d/10-mail.conf
    lines:
      - mail_location = mbox:~/mail
      - mail_privileged_group = mail
  - file: /etc/dovecot/conf.d/10-auth.conf
    lines:
      - disable_plaintext_auth = yes
      - auth_username_format = %n
      - auth_mechanisms = plain
  - file: /etc/dovecot/conf.d/10-ssl.conf
    lines:
      - ssl = required
      - ssl_cert = </vagrant/ssh/MyCertificate.crt
      - ssl_key = </vagrant/ssh/MyKey.key
      - ssl_prefer_server_ciphers = yes
      - ssl_protocols = !SSLv3 !TLSv1 !TLSv1.1
#  - file: /etc/dovecot/conf.d/15-mailboxes.conf
#    insert_after: '  mailbox Sent {'
#    lines:
#      - "    auto = create"

# Blocks to be entered with blockinfile module
#
blocks_in_file:
  - file: /etc/postfix/master.cf
    block: |
      submission     inet     n    -    y    -    -    smtpd
        -o syslog_name=postfix/submission
        -o smtpd_tls_security_level=encrypt
        -o smtpd_tls_wrappermode=no
        -o smtpd_sasl_auth_enable=yes
        -o smtpd_relay_restrictions=permit_sasl_authenticated,reject
        -o smtpd_recipient_restrictions=permit_mynetworks,permit_sasl_authenticated,reject
        -o smtpd_sasl_type=dovecot
        -o smtpd_sasl_path=private/auth
  - file: /etc/dovecot/conf.d/10-master.conf
    insert_after: "service auth "
    block: |2
        unix_listener /var/spool/postfix/private/auth {
          mode = 0660
          user = postfix
          group = postfix
        }
  - file: /etc/dovecot/conf.d/10-master.conf
    insert_after: "service lmtp "
    block: |2
        unix_listener /var/spool/postfix/private/dovecot-lmtp {
          group = postfix
          mode = 0600
          user = postfix
        }

##############################################################################
# Role: setup_email_server - END
##############################################################################