##############################################################################
# Role: yum_install - START
##############################################################################

# Repositories to add using yum-config-manager
#
repos_to_add:
  - https://download.docker.com/linux/centos/docker-ce.repo

# Every package is defined with its name and state - so we
# can have possibility to remove or update package if needed.
#
# Also packages can have svc dict assigned with them, if
# we need to enable and start service after package installation.
#
yum_packages_to_install:
  - name: epel-release
    state: present
  - name: yum-utils
    state: present
  - name: device-mapper-persistent-data
    state: present
  - name: lvm2
    state: present
  - name: containerd.io
    state: present
  - name: docker-ce-3:18.09.1-3.el7
    state: present
    svc:
      name: docker
      enabled: yes
      svc_state: started
  - name: docker-ce-cli
    state: present
  - name: python3
    state: present
  - name: net-tools
    state: present
  - name: wget
    state: present
  - name: unzip
    state: present

##############################################################################
# Role: yum_install - END
##############################################################################



##############################################################################
# Role: download_packages - START
##############################################################################

# packages_to_download - list of package to download, defined by url and service name
#
packages_to_download:
  - pkg_url: https://github.com/prometheus/node_exporter/releases/download/v0.18.1/node_exporter-0.18.1.linux-amd64.tar.gz
    pkg_ext: tar.gz
    svc_name: node_exporter
    svc_binary: node_exporter
  - pkg_url: https://github.com/ncabatoff/process-exporter/releases/download/v0.6.0/process-exporter-0.6.0.linux-amd64.tar.gz
    pkg_ext: tar.gz
    svc_name: process_exporter
    svc_binary: process-exporter
    svc_config: process_exporter.yml
  - pkg_url: http://packages.psychotic.ninja/7/base/x86_64/RPMS/stress-1.0.4-14.el7.psychotic.x86_64.rpm
    pkg_ext: rpm
    svc_name: stress
  - pkg_ext: py
    svc_name: stress_generator
    svc_binary: stress_generator.py
  - pkg_url: https://www.rainloop.net/repository/webmail/rainloop-community-latest.zip
    pkg_ext: zip
    svc_name: rainloop

# svc_unit_location - location of service unit file
# svc_binary_location - location of service binaries
# pkg_dest - destination folder for download
svc_unit_location: /etc/systemd/system
svc_binary_location: /usr/share
pkg_dest: /home/vagrant/temp

##############################################################################
# Role: download_packages - END
##############################################################################



##############################################################################
# Role: setup_docker - START
##############################################################################

# Docker services to run with docker compose
#
docker_svcs:
  - name: nginx
    image: nginx
    container_name: nginx
    ports:
      - "80:80/tcp"
    volumes:
      - "/tmp/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "/tmp/rainloop:/var/www/rainloop"
    depends_on:
      - webmail
  - name: webmail
    image: php:fpm-alpine
    container_name: webmail
    ports:
      - "9000:9000/tcp"
    volumes:
      - "/tmp/rainloop:/var/www/rainloop"
  - name: cadvisor
    image: gcr.io/google_containers/cadvisor:v0.35.0
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"

##############################################################################
# Role: setup_docker - END
##############################################################################